name: Terraform Docs

on:
  push:
    branches:
      - main
      
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Specify the version of Terraform you use

      - name: Install terraform-docs
        run: |
          curl -sSLo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.18.0/terraform-docs-v0.18.0-linux-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          sudo mv terraform-docs /usr/local/bin/

      - name: Generate Terraform docs
        uses: terraform-docs/gh-actions@v1
        with:
          output_file: README.md
          output_mode: inject
          # Optionally specify which files to render
          # terraform_dir: ./path/to/terraform/configs

      - name: Commit and push changes
        if: github.ref == 'refs/heads/main'
        uses: EndBug/add-and-commit@v9
        with:
          add: 'README.md'
          message: 'Update Terraform documentation'
          author_name: 'github-actions'
          author_email: 'actions@github.com'
